### ISSUE TITLE
Unary Tuples

### ISSUE THREAD

**Issue by NeuralCoder3** [AnyDSL/thorin2#122]
A unary tuple is normalized to its content:
```
<<1; T>>
T
[T]
```
are all the same type and
```
<1;42>
42
(42)
```
are the same value.

This usually is helpful and senseful.
But it leads to errors in edge cases:
```
    n:.Nat,
    i:.Idx n,
    t:<< n; [I32,I32]>>,
``` 
If `n` is specialized to be `1`, the array degenerates to a scalar.
Therefore, the projection 
```
t#i#(1:(.Idx 2))
```
is invalid.

Example:
https://github.com/NeuralCoder3/thorin2/blob/matrix_dialect/lit/core/unary_tuple.thorin

Call:
``` 
./build/bin/thorin -o - lit/core/unary_tuple.thorin
``` 

Error:
``` 
lit/core/unary_tuple.thorin:13:13-13:15: error: index '0:(.Idx 1)' does not fit within arity '2'
``` 

Solution idea (possible related to an earlier discussion we had):
Also normalize the projection away.
A projection with `0:(.Idx 1)` is the identity.

**Comment by NeuralCoder3** [comment]
I think the normalization is already implemented in 
https://github.com/AnyDSL/thorin2/blob/master/thorin/world.cpp#L191

But this code snippet does not seem to be applicable in this case for some reason.

**Comment by leissa** [comment]
As kind of related comment. We currently have many overloads like:
```
def->proj(i)
```
and
```
def->proj(n, i)
```
I'm seriously considering removing the first variant. It's just too easy to shoot yourself in the foot.
