### ISSUE TITLE
Function body is not read correctly

### ISSUE THREAD

**Issue by NeuralCoder3** [AnyDSL/thorin2#134]
For instance, `pow_ad_eval_simpl2_mem.thorin` from
https://github.com/NeuralCoder3/thorin2/blob/autodiff/lit/clos/pow_ad_eval_simpl2_mem.thorin

can not be read by thorin.
```
./build/bin/thorin ./lit/clos/pow_ad_eval_simpl2_mem.thorin -o - -VVVV
```

Directly produces the error
```
In def aug_f_745675_660796_216256:
Assertion "some operands are set, others aren't"' failed.
Filter: 0:(.Idx 2)
Body: <nullptr>
```

**Comment by NeuralCoder3** [comment]
The error was that at some points the memory argument was not passed.
The error message seems to be at the wrong place / non-informative.

**Comment by leissa** [comment]
Ah, I just debugged it. Problem is that the filter has already been set but not the body. Thus, the assert. I'm considering removing this assertion as it causes more trouble and confusion than it actually helps.
