### ISSUE TITLE
unexpected normalizer behavior 

### ISSUE THREAD

**Issue by NeuralCoder3** [AnyDSL/thorin2#149]
An older issue that surfaces again:

Normalizers act only on fully applied terms.
This is helpful in general as we want to normalize using the arguments.
But the determination of whether something is fully applied to not fine enough.
Ideally, the normalizer should fire at the moment the axiom is applied to all of **its own** arguments.
The number of arguments / the moment of full application could be determined using the type of the axiom.
This would not work perfectly for axioms that always return a function. But this is also currently a problem and it would be an expected edge case.

If the axiom is higher-order and returns a function, the normalizer is given the arguments that are applied to the final function as `arg` which might be confusing.
Therefore, one needs to collect all arguments from nested applications, work with the first few, and reapply the others in the end.

Example:
```
.ax %direct.cps2ds: Π [T: *, U: *] -> (.Cn [T, .Cn U]) -> (T -> U), normalize_cps2ds;
```

**Comment by leissa** [comment]
Ah. good point.

**Comment by leissa** [comment]
Trouble is, if we have an axiom of type `A -> B -> C` we don't know whether this is an axiom that returns `C` or `B -> C`. I think the only proper way to deal with that is to also provide the info when declaring the axiom and defaulting to `C` (what is happening rn). Thoughts?
