### ISSUE TITLE
Rewrite Phase Assertion Issue

### ISSUE THREAD

**Issue by NeuralCoder3** [AnyDSL/thorin2#155]
There might be a bug in the rewrite phase or in my usage thereof.

In [277d500](https://github.com/NeuralCoder3/thorin2/commit/277d50087e082ce5aad7373fc0e81437ac942e08) in 
https://github.com/NeuralCoder3/thorin2/blob/matrix_dialect/dialects/matrix/passes/lower_matrix_lowlevel.cpp#L74

we have a minimal rewrite phase that just rewrites with the identity.

But for instance `./build/bin/thorin -o - -VVVV -d matrix lit/matrix/init_const_no_ret.thorin` fails at the assumption that
the world of the rewritten def or the gid is different.

**Comment by fodinabor** [comment]
Didn't we have the `if (scope != nullptr && !scope->bound(old_def)) return old_def;` there in earlier versions of `rewrite` so that one doesn't end up rewriting axiom definitions?

**Comment by NeuralCoder3** [comment]
> Didn't we have the `if (scope != nullptr && !scope->bound(old_def)) return old_def;` there in earlier versions of `rewrite` so that one doesn't end up rewriting axiom definitions?

The raised assertion is in https://github.com/AnyDSL/thorin2/blob/master/thorin/def.cpp#L97.

Which location do you mean?

**Comment by fodinabor** [comment]
The assert basically says, that you're trying to rebuild an axiom in its origin world (the rebuild seems to actually change something, since the gid is changed, probably a nominal parameter?). That happens since the phase just rewrites everything by delegating to the `Rewriter`.

An older version of the rewrite, hat that check:
https://github.com/AnyDSL/thorin2/blob/0d4799baf15481531eb12d5462081b69c8773abb/thorin/rewrite.cpp#L11

**Comment by leissa** [comment]
It's still there. There is now the `ScopeRewriter` that inherits from `Rewriter` which does this check. However, `RWPhase` only inherits from `Rewriter` since it does not argue about any Scopes.

**Comment by leissa** [comment]
Okay, I tried the example. Per se there is nothing wrong with rewriting axioms as long as the resulting axiom is either in a new world or the exact same axioms again. This is what the assertion tells us. Now what happens in this example is that the **type** of the axiom changes. But I just checked: Both types are alpha-equiv. So, I'd suggest to change `Axiom::rebuild` to this:
```c++
const Def* Axiom    ::rebuild(World& w, const Def* t, Defs  , const Def* dbg) const {
    if (w ! = world()) return w.axiom(normalizer(), curry(), trip(), t, dialect(), tag(), sub(), dbg);
    assert(w.checker().equiv(t, type(), dbg));
    return this;
}
```

**Comment by NeuralCoder3** [comment]
With the merge of master, the old problem is resolved.
But now the rewrite phase seems to not change anything.
It reports that the def that should be rewritten is encountered and the correct new def is returned in `rewrite_structural`.
But the code does not change. The old def remains in the code.

Example command: `./build/bin/thorin -o - -VVVV -d matrix lit/matrix/init_no_ret.thorin` .

**Comment by NeuralCoder3** [comment]
I think the wrong phase is used proceeding after the rewrite phase.
If I for instance make the old externals internal, the world becomes empty.
This indicates that the new world where everything happens is discarded.
