### ISSUE TITLE
Automatic Dialect Loading

### ISSUE THREAD

**Issue by NeuralCoder3** [AnyDSL/thorin2#171]
We probably should load dialects automatically.
Currently, the user has to specify the loaded dialects using `-d [dialect]`.

A fine control might be helpful during development (for instance ignoring closure conversion phases).
But we can handle these settings (disabling some phases) also using the opt primitives.
Additionally, it is quite easy to forget to load a dialect and wonder why some passes are not executed (see #169).

One option would be to always load all available phases.

Another would be to load all dialects imported in the file.
This however misses dialects that are recursively needed (e.g. maths in matrix).
If we recursively look up imported dialects, we end up again loading all of them as opt imports nearly every other dialect.

**Comment by leissa** [comment]
Maybe a `--bootstrap` option is enough to not load the plugins and only parse the `*.thorin` files. If `--bootstrap` is not present all plugins should be auto-loaded.

**Comment by NeuralCoder3** [comment]
We have something similar already:
If not calling with `--output-h`, we automatically load `core`, `mem`, `compile`, `opt`.
So the only difference would probably be to remove the `-d` option and to search for all available dialects instead of this hardcoded list.

**Comment by leissa** [comment]
Right. `--output-h` implies "bootstrap" mode.
