### ISSUE TITLE
Shadowing for variables

### ISSUE THREAD

**Issue by NeuralCoder3** [AnyDSL/thorin2#172]
It would be helpful to allow the shadowing of local declarations in the thorin syntax.
This only affects parsing and does not change existing programs. It just allows additional programs that were invalid previously.

One case where this syntax would be helpful is the memory monad:
```rust
    .let (mem1, m1_t) = %matrix.transpose ((m,k), %math.F (p,e)) (mem ,m1);
    .let (mem2, m2_t) = %matrix.transpose ((k,l), %math.F (p,e)) (mem1,m2);
    .let (mem3, m1_s) = %matrix.prod      (m,l,k, (p,e))         (mem2,ms,m2_t);
    .let (mem4, m2_s) = %matrix.prod      (k,m,l, (p,e))         (mem3,m1_t,ms);
    .let (mem5, result) = %matrix.prod    (m,k,l, (p,e))         (mem4,m1,m2);
    pb_ret (mem5,m1_s,m2_s)
```
is cumbersome to write and error-prone as one needs to enumerate all memory instances.
It is tedious to add a new operation in between old ones.

With shadowing, the code becomes
```rust
  .let (mem, m1_t) = %matrix.transpose ((m,k), %math.F (p,e)) (mem ,m1);
  .let (mem, m2_t) = %matrix.transpose ((k,l), %math.F (p,e)) (mem,m2);
  .let (mem, m1_s) = %matrix.prod      (m,l,k, (p,e))         (mem,ms,m2_t);
  .let (mem, m2_s) = %matrix.prod      (k,m,l, (p,e))         (mem,m1_t,ms);
  .let (mem, result) = %matrix.prod    (m,k,l, (p,e))         (mem,m1,m2);
  pb_ret (mem,m1_s,m2_s)
```
Which is easier to read and write.

Pro:
* Easier to write
* Clear from the context
* Used from other languages

Contra:
This syntax steps a bit away from the sea of nodes approach.
We use the explicit order of the linearized text format.
However, we already use this order to reuse names in different scopes.
Also, the linearized order is inherently connected to the way, we write thorin programs (as text).

**Comment by leissa** [comment]
Maybe we can add a special token to make a rebinding possible and stress that in the syntax. Sth like this:
```ml
.let ('mem, x) = ...
.let ('mem, y) = ...
```
