### ISSUE TITLE
Inconsistent constant folding of one-element tuples

### ISSUE THREAD

**Issue by f-fries** [AnyDSL/thorin2#23]
One-element tuples are not constant folded away if the elements' type is a nom sigma.
I.e 
``` c++
// The type is simplified:
auto type = w.nom_sigma(w.kind(), 2);
type->set({w.type_int(), w.type_int()});
ASSERT_EQ(type, w.sigma({type}))

// The value is not simplified:
auto v = w.tuple(type, {w.lit_int(42), w.lit_int(1337)});
ASSERT_EQ(v, w.tuple({v}));   // < fails
```
([complete test](https://github.com/AnyDSL/thorin2/blob/6a1ec40a0088817a2866f6f5c84fa93179ca1df9/gtest/test.cpp))

There seems to be a similar issue when the one-tuple appears inside the struct:
```
struct Pos {
    pos: (int, int)
}

extern fn f(wrapped: Pos) -> int {
    let (x:int, y:int) = wrapped.pos; x
}
```
yields
```
Pos_8079: ★ = {
    [«2∷nat; i32»]
}
        
cc_f_8103: Cn [:mem, Pos_8079, Cn [:mem, i32]]: (_8132, _8143, _8127) = {
    _8151: ⊥∷★ = _8122 (_8132, _8143#0∷i0#0∷i1);
    λ@(0∷i1) _8151
}
            
    _8122: Cn [:mem, i32]: (_8259, _8264) = {
        _8129: ⊥∷★ = _8127 @_8122;
        λ@(0∷i1) _8129
    }
```
Here we get a a index of type `i0` which the BE can't handle.

**Comment by leissa** [comment]
Regarding the first issue:
This is the intended behavior. When talking about nominal 1-Tupel-Sigmas, we cannot just remove them:
1. Since you can set the body later on, we just cannot do this all the time.
2. Consider this example: 
    ```rust
    struct List {
        next: &List
    }
    ``` 
    There is no way, to remove this 1-Tupel-Sigma.
    
For the second issue:
I think this is just a missing case in the llvm backend. I will investigate this.

**Comment by leissa** [comment]
Fixed. Let me know if there are still probls.
